language: groovy
jdk:
  - openjdk17
sudo: false
branches:
  only:
    - grails4-oidc-openapi-queueonly
    - develop
    - master
    - /^feature.*$/

before_install:
  - sudo mkdir -p /data/fieldguide
  - sudo chmod o+xw /data
  - sudo chmod o+xw /data/fieldguide

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

install:
  - 'travis_wait 30 ./gradlew clean'
  - './gradlew assemble'

after_success:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && travis_retry ./gradlew publish'
env:
  global:
    - JAVA_TOOL_OPTIONS=-Dhttps.protocols=TLSv1.2
    - secure: VnkEyGd04MU+vQg8okIFx5IycrGJwks33zENsAJLkVRdZHR9BAaTlszbgECaJ8JVEES2VOnZuerR/1LUDscpklTElLyZiry3lRHPTeoXEhWBEQ2nvzS6O+91hbRWln5ViDaLNSidLYnrwwlKIUsUeQY+nkZfluvOfl61LkbI3KE=
    - secure: DwNaQxzPOGIVoVzt3WOGthnWai+o0dLrGBBNn/mp0/cd4ZfGGioWI0WrIu4yxeg4kdbcgvt7f0ubhID6ove6g6i0p7339I58GXCSz4Bn+DDv0dzj0uwZ72f+9KOYvMyYzDdjN6arQUTkOaCnQRBab7+Cc/+kjkjKHvpe7NCVMCc=
